### ISSUE TITLE
Support for delayed job

### ISSUE THREAD

**Issue by html5fun** [xing/paperclip-storage-ftp#31]
Couple of questions - Is background processing (for example, using delayed jobs) for uploading/processing of  images  already supported? Are simultaneous image uploads supported?  
Many thanks for adding ftp support to paperclip. Made life a lot easier

**Comment by boosty** [comment]
Hi @html5fun, 

there is no explicit support for background processing in this gem. Since this gem only provides a storage adapter for paperclip, I don't think this gem will ever contain specific code for background processing. I haven't tried it, but maybe https://github.com/jrgifford/delayed_paperclip/ just works together with this gem?

Regarding simultaneous image uploads: When using multiple ftp servers, we upload to them in parallel (see https://github.com/xing/paperclip-storage-ftp/blob/master/lib/paperclip/storage/ftp.rb#L40-L47). 
Again, we are just providing a storage adapter, so that's probably the only thing this gem will ever do in this regard.

Does this answer your question?

**Comment by html5fun** [comment]
Thanks for your detailed reply. I will try out the delayed_paperclip gem and check if paperclip-storage-ftp will work with it.  Will let you know if it works.

Thanks again.
